suzzapps/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('ttours/',include('ttours.urls')),
    path('admin/', admin.site.urls)
]

ttours/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'ttours'
urlpatterns = [
    path('', views.IndexView.as_view(), name='ttindex'),
    path('<int:pk>/', views.SeasonView.as_view(), name='season'),
    path('<int:pk>/match', views.MatchView.as_view(), name='match',),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ttours/models.py
from django.db import models
import datetime
from django.utils import timezone

class Season(models.Model):
    start_date=models.DateTimeField('Season start date')
    end_date=models.DateTimeField('Season end date')
    name=models.CharField(max_length=200)
    last_modified=models.DateTimeField(default=timezone.now)
    def is_current_season(self):
        now=timezone.now()
        return self.start_date<=now<=self.end_date
    def __str__(self):
       return self.name

class Player(models.Model):
    player_name=models.CharField(max_length=25)
    created_date=models.DateTimeField('Date Joined')
    pic_path=models.CharField(max_length=300)
    last_modified=models.DateTimeField(default=timezone.now)
    def __str__(self):
       return self.player_name

class Season_Players(models.Model):
    player=models.ForeignKey(Player,on_delete=models.CASCADE)
    season=models.ForeignKey(Season,on_delete=models.CASCADE)
    rating=models.IntegerField(default=2000)
    last_match=models.DateTimeField(default=timezone.now)
    wins=models.IntegerField(default=0)
    losses=models.IntegerField(default=0)
    win_percentage=models.DecimalField(default=0,max_digits=5,decimal_places=2)
    last_modified=models.DateTimeField(default=timezone.now)
    class Meta:
        ordering=['-rating']
    def getPlayerName(self):
        return self.player.player_name
    def __str__(self):
       return self.player.player_name + '('+self.season.name+')'

class Match(models.Model):
    match_time=models.DateTimeField(default=timezone.now)
    player1=models.ForeignKey(Season_Players,on_delete=models.CASCADE,related_name='player1')
    player2=models.ForeignKey(Season_Players,on_delete=models.CASCADE,related_name='player2')
    season=models.ForeignKey(Season,on_delete=models.CASCADE,default=1)
    player1_score=models.IntegerField(default=0)
    player2_score=models.IntegerField(default=0)
    player1_rating_delta=models.IntegerField(default=0)
    player2_rating_delta=models.IntegerField(default=0)
    winner=models.ForeignKey(Season_Players,on_delete=models.CASCADE,related_name='winner')
    last_modified=models.DateTimeField(default=timezone.now)
    class Meta:
        ordering=['-match_time']
    def save(self, *args, **kwargs):
        if self.player1 == self.player2:
            raise Exception('Player 1 cannot be Player 2')
        super(Match, self).save(*args, **kwargs)
        if self.player1_score == self.player2_score:
            raise Exception('How bout you shitters play till someone wins')
        super(Match, self).save(*args, **kwargs)
    def __str__(self):
       return self.player1.player.player_name+' vs '+self.player2.player.player_name + ' ['+self.season.name+']' +' ('+"{:%B %d, %Y}".format(self.match_time)+')'


# Create your models here.

ttours/forms.py
from django.forms import ModelForm,Textarea
from .models import Match


# Create the form class.
class MatchForm(ModelForm):
    def __init__(self, *args,**kwargs):
        super(MatchForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Match
        fields=['player1','player2','player1_score','player2_score']


ttours/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.utils import timezone
from.forms import MatchForm
from .models import Player,Season,Season_Players,Match

class IndexView(generic.ListView):
    template_name='ttours/index.html'
    context_object_name='seasons'
    def get_queryset(self):
        return Season.objects.all().order_by('-start_date')

class SeasonView(generic.DetailView):
    template_name='ttours/season.html'
    model=Season
    def get_context_data(self, **kwargs):
         context = super(SeasonView, self).get_context_data(**kwargs)
         context['matches'] = Match.objects.filter(season_id=self.object.id)[:10]
         return context

class MatchView(generic.FormView):
    template_name='ttours/addmatch.html'
    form_class=MatchForm
    def get_success_url(self, **kwargs):
        return reverse_lazy('ttours:season', kwargs={'pk': self.kwargs['pk']})

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form, **kwargs)
        else:
            return self.form_invalid(form)

    def form_valid(self, form,**kwargs):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        match=form.save(commit=False)
        player1=form.cleaned_data['player1']
        player2=form.cleaned_data['player2']
        player1_score=form.cleaned_data['player1_score']
        player2_score=form.cleaned_data['player2_score']
        match.season=Season.objects.get(id=self.kwargs['pk'])
        match.match_time=timezone.now()
        percent=1 / (1 + 10 ** ((player2.rating - player1.rating) / 400))
        win=round((1-percent)*50)
        loss=round((0-percent)*50)

        if(player1_score>player2_score):
            match.player1_rating_delta=win
            match.player2_rating_delta=-win
            player1.rating+=win
            player2.rating-=win
            player1.wins+=1
            player2.losses+=1
            match.winner=player1
        else:
            match.player1_rating_delta=loss
            match.player2_rating_delta=-loss
            player1.rating+=loss
            player2.rating-=loss
            player1.losses+=1
            player2.wins+=1
            match.winner=player2
        player1.last_match=timezone.now()
        player2.last_match=timezone.now()
        player1totgames=player1.wins+player1.losses
        player2totgames=player2.wins+player2.losses
        if(player1.wins>0):
            player1.win_percentage=round((player1.wins/player1totgames)*100,2)
        if(player2.wins>0):
            player2.win_percentage=round((player2.wins/player2totgames)*100,2)
        player2.save()
        player1.save()
        form.save()
        return super().form_valid(form)

class PlayerView(generic.ListView):
    template_name='ttours/players.html'
    context_object_name='players'
    def get_queryset(self):
        return Season.objects.all()




# Create your views here.

ttours/templates/ttours/addmatch.html
{% extends 'ttours\base.html' %}
{% load widget_tweaks %}
{% block nav %}
<a class="nav-link" href="{% url 'ttours:ttindex' %}">Seasons</a>
<a class="nav-link" href="#">Players</a>
<a class="nav-link" href="#">My Profile</a>
<!-- add join season navbutton, disable if already in season-->
{% endblock %}
{% block content %}
<h1>Record a match</h1>
<br>
<div style="width:40vw;text-align: center;align-content: center;">
<form method="POST">{%csrf_token%}
    {{ form.non_field_errors }}

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field.errors }}
      {{ hidden_field }}
    {% endfor %}
    
    <table style="margin: 0 auto;">
      {% for field in form.visible_fields %}
        <tr>
          <th>{{ field.label_tag }}</th>
          <td>
            {{ field.errors }}
            {% render_field field%}
            {{ field.help_text }}
          </td>
        </tr>
      {% endfor %}
    </table>
    <input type="submit" value="Create Match" style="margin: 0 auto;">
</form>
</div>
<script>
    var x=document.getElementById("id_player1")
    
</script>
{% endblock %}

ttours/templates/ttours/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'ttours/style.css' %}">
  </head>
  <body class="text-center">

        <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
          <header class="masthead mb-auto">
            <div class="inner">
              <h3 class="masthead-brand">TTours</h3>
              <a class="masthead-brand">
                    <img src="{% static "ttours/logo.png" %}" alt="" width="60" height="30">
              </a>
              <nav class="nav nav-masthead justify-content-center">
                {% block nav %}
                {% endblock %}
              </nav>
            </div>
          </header>
          
          <main role="main" class="inner cover" style="overflow:auto;"id="style-4">
            
                    {% block content %}
                    {% endblock %}
            
          </main>
    
          <footer class="mastfoot mt-auto">
            <div class="inner">
              <p><!-- footer stuff --></p>
            </div>
          </footer>
        </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

ttours/templates/ttours/index.html
{% extends 'ttours\base.html' %}
{% block nav %}
{% if seasons %}
<a class="nav-link active" href="{% url 'ttours:ttindex' %}">Seasons</a>
<a class="nav-link" href="#">Players</a>
<a class="nav-link" href="#">My Profile</a>
{% endif %}
{% endblock %}
{% block content %}
{% if seasons %}
        <h1 class="cover-heading">Seasons</h1>
        <br>
        <span class="row">
            <div class="col col-md-4 col-sd-2"><p class="resp">Season</p></div>
            <div class="col col-md-4 col-sd-5"><p class="resp">Start</p></div>
            <div class="col col-md-4 col-sd-5"><p class="resp">End</p></div>
        </span>
        {% for season in seasons %}
        <a href="{% url 'ttours:season' season.id %}">
            
        <span class="row">
                <div class="col col-md-4 col-sd-4 {%if season.is_current_season%} current{%endif%}"><p class="resp1"> {{ season.name }}</p></div>
                <div class="col col-md-4 col-sd-4 {%if season.is_current_season%} current{%endif%}"><p class="resp">{{ season.start_date|date:"d-M-Y" }}</p></div>
                <div class="col col-md-4 col-sd-4 {%if season.is_current_season%} current{%endif%}"><p class="resp">{{ season.end_date|date:"d-M-Y" }}</p></div>
        </span>
        </a>


        {% endfor %}
{% else %}
    <p>No seasons created</p>
{% endif %}
{% endblock %}

ttours/templates/ttours/season.html
{% extends 'ttours\base.html' %}
{% block nav %}
<a class="nav-link active" href="{% url 'ttours:ttindex' %}">Seasons</a>
<a class="nav-link" href="#">Players</a>
<a class="nav-link" href="#">My Profile</a>
<a class="nav-link" href="#">Join Season</a>
<a class="nav-link" href="{% url 'ttours:match' season.id%}">Record Match</a>
<!-- add join season navbutton, disable if already in season-->
{% endblock %}
{% block content %}
{% if matches %}
        <br>
        <h1 class="cover-heading">Last 10 Matches</h1>
        <br>
        <span class="row">
            <div class="col col-md-3"><p class="resp">Player 1</p></div>
            <div class="col col-md-3"><p class="resp">Player 2</p></div>
            <div class="col col-md-3"><p class="resp">Winner</p></div>
            <div class="col col-md-3"><p class="resp">Match time</p></div>
        </span>
        {% for match in matches  %}
            
        <span class="row">
                <div class="col col-md-3 "><p class="resp">{{match.player1.getPlayerName}} ({{match.player1_score}}) [{{match.player1_rating_delta}}]</p></div>
                <div class="col col-md-3 "><p class="resp">{{match.player2.getPlayerName}} ({{match.player2_score}}) [{{match.player2_rating_delta}}]</p></div>
                <div class="col col-md-3 "><p class="resp">{{match.winner.getPlayerName}}</p></div>
                <div class="col col-md-3 "><p class="resp">{{match.match_time|date:"d-M-Y"}}</p></div>
        </span>
        {% endfor %}
{% else %}
    <p>No matches in season</p>
{% endif %}

{% if season %}
        <br>
        <h1 class="cover-heading">Players</h1>
        <br>
        <span class="row">
            <div class="col col-md-3"><p class="resp">Player</p></div>
            <div class="col col-md-2"><p class="resp">Rating</p></div>
            <div class="col col-md-2"><p class="resp">Win/Loss</p></div>
            <div class="col col-md-2"><p class="resp">Win%</p></div>
            <div class="col col-md-3"><p class="resp">Last Match</p></div>
        </span>
        {% for sp in season.season_players_set.all  %}
            
        <span class="row">
                <div class="col col-md-3"><p class="resp">{{sp.getPlayerName}}</p></div>
                <div class="col col-md-2"><p class="resp">{{sp.rating}}</p></div>
                <div class="col col-md-2"><p class="resp">{{sp.wins}}/{{sp.losses}}</p></div>
                <div class="col col-md-2"><p class="resp">{{sp.win_percentage}}%</p></div>
                <div class="col col-md-3"><p class="resp">{{sp.last_match|date:"d-M-Y"}}</p></div>
        </span>
        {% endfor %}
{% else %}
    <p>No season</p>
{% endif %}
{% endblock %}